### ISSUE TITLE
Not Exist auth functions

### ISSUE THREAD

**Issue by makorne** [mailru/tarantool-authman#10]
Не знаю, что это - баг или не баг, а фишка, но объяснения не найти..
В тарантуле тесты проходят, вручную тоже все делается.
Но почему вызываемые функции не находятся даже при вызове func.exists?

```
ok, user = auth.registration('example2@mail.ru')
---
...

 box.schema.func.exists('auth.registration')
---
- false
...

 box.schema.func.exists('api.registration')
---
- false
...
 box.schema.func.exists('registration')
---
- false
...
box.schema.func.exists('auth')
---
- false
```
...
Для коннектора нужны названия функций, а они и в тарантуле не доступны :(

**Comment by LinnikD** [comment]
Как был инициализирован инстанс? Вероятно дело в том, что функции не были созданы через `box.schema.func.create`. Иначе `box.schema.func.exists('auth.registration')` должен быть true. При необходимости `box.schema.func.create` для необходимых фукнкций можно сделать после создания инстанса

**Comment by makorne** [comment]
О, спасибо за мысль!
Додуматься что нужно оказавается создать функцию, которая и так отлично работает, совсем не тривиально...

Пакет ставился дебом, уж не знаю как там по шайтански создавались эти невидимые функции..
tarantoolctl start tarantool-authman.

**Comment by LinnikD** [comment]
Вот как раз в `etc/tarantool/instance.enabled/tarantool-authman.lua` можно зарегистрировать необходимые функции с помощью `box.schema.func.create`  - https://tarantool.io/en/doc/1.7/book/box/box_schema.html#box-schema-func-create. 

Я к сожалению не знаком с этим функционалом Тарантула и не видел практик когда в приложениях хранимки создавались именно так, возможно он изначально был разработан только для core функционала.

Если проблема решена, то я закрою issue, спасибо за интересный вопрос)

**Comment by makorne** [comment]
А как тогда подразумевалось использование апи из других языков, если к функции через стандартный коннектор доступ не предусмотрен? 

 Может я что-то не понимаю как вообще правильно это приложение прикручивать к другим языкам?
Понятно, что можно приписать создание функций, но не хотелось бы городить костыли, которые потом каждый раз ставить в добавок к самому приложению.

Или все же пропишите создание функций в самом приложении, думаю многим понадобится.

**Comment by LinnikD** [comment]
Из какого языка и каким коннектором пользуетесь? И какой код написан сейчас в `etc/tarantool/instance.enabled/tarantool-authman.lua`?

Вообще использование коннектора не требовало создания никаких доп. функций. Если переменная `auth` объявлена как глобальная, то она доступна для вызова через метод call коннектора.

**Comment by makorne** [comment]
Язык с. Коннектор с по тарантул-хелпу.
код - из вашего примера, даже конфигурацию социалок пока не вписывал, должно ж и с простым емайлом работать
```
box.cfg {
    listen = 3302,
}

local config = {
   -- configuration table, details below
}
auth = require('authman').api(config)
```
Вообще неочень понятно, измененным содержанием 
my_config.lua нужно заменить стороку  "-- configuration table, details below"
или где-то сохранить, и как-то вызывать my_config.lua прописав его вызов где-то чтобы получить значения по return?

**Comment by LinnikD** [comment]
Коннекторы которыми я пользовался (perl, python, golang) не воспроизводили подобной проблемы и давали возможность обратиться к глобальным переменным. Вероятно это какая-то особенность C коннектора.

Конфиг можно реализовать так `auth-config.lua`:
```
return {
   secret = '...',
}
```
И в tarantool-authman.lua:
```

**Comment by makorne** [comment]
Спасибо, пожалуй можно и закрывать.

**Comment by makorne** [comment]
Странно, если делать по этому варианту, то ошибку выдает на строке local config = 
```
Failed to check instance file '/etc/tarantool/instances.enabled/tarantool-authman.lua:6: function arguments expected near '=''
Error while checking syntax: halting
```

**Comment by makorne** [comment]
После регистрации функции auth.registration(email, user_id)
Стало закладывать в базу, и что-то отвечать
`
dd 0 0 0 2 c3 85 a9 69 73 5f 61 63 74 69 76 65 c2 a7 70 72 6f 66 69 6c 65 c0 a2 69 64 d9 24 66 63 34 30 38 33 63 35 2d 36 64 30 38 2d 34 39 36 33 2d 61 34 61 66 2d 31 62 31 36 65 66 33 36 64 36 65 31 a5 65 6d 61 69 6c ad 75 72 72 72 61 40 6d 61 69 6c 2e 72 75 a4 63 6f 64 65 d9 20 66 36 66 34 34 38 31 35 62 36 62 35 65 39 39 65 39 66 39 64 35 64 32 36 30 39 37 36 61 31 33 62
`
Есть мысли как это расшифровать?
mp_typeof сообщает что это  MP_STR.
Но mp_decode_str падает на 235 в mp_load_u8

Или может проще как-то использовать встроенный в тарантул http сервер для всей регистрации-авторизации, чтоб на выходе был заавторизированный юзер?
Его данные можно было бы брать уже прямо из базы.

**Comment by LinnikD** [comment]
Похоже дело в имени файла `/etc/tarantool/instances.available/auth-config`. Не хватает расширения .lua - `/etc/tarantool/instances.available/auth-config.lua`. 

Так же в таких случаях стоит посмотреть на содержимое переменной `package.path`. [Подробнее здесь](http://lua-users.org/wiki/PackagePath).

**Comment by makorne** [comment]
Нет, так я тоже пробовал
`2018-06-06 16:31:16.180 [10532] main/101/tarantool-authman tarantoolctl:521 E> Start failed: /etc/tarantool/instances.enabled/tarantool-authman.lua:4: module '/etc/tarantool/instances.available/auth-config.lua'  not found:
        no field package.preload['/etc/tarantool/instances.available/auth-config.lua']
        no file './/etc/tarantool/instances/available/auth-config/lua.lua'
        no file './/etc/tarantool/instances/available/auth-config/lua/init.lua'`

`ls -la /etc/tarantool/instances.available/auth-config.lua

-rwxrwxr-x 1 root root 1003 Jun  5 18:03 /etc/tarantool/instances.available/auth-config.lua`

А Package Path  должен быть бесполезным, тут же абсолютный путь указан.

**Кстати!!** Вся библиотека посвящена авторизации,  но не сказано - а как лучше использовать ее продукт - полученную сессию юзера? Где лучше ее помещать у юзера - в куках или  в headers, еще как-то? Вчерашняя статья говорит что нельзя в куках,  [https://habr.com/company/oleg-bunin/blog/412855/](url)
Другая статья наоборот заявляет  что куки лучше всего и The only correct CSRF mitigation is a CSRF token. The session mechanism is not relevant here.[http://cryto.net/~joepie91/blog/2016/06/13/stop-using-jwt-for-sessions/](url) 
Как рекомендуете ВЫ? Может как пример какой-то сайт где используется, посмотреть?

**Comment by LinnikD** [comment]
Импорт в lua происходит по относительному пути. Эти пути конкатинируются с путями из `package.path`. Например: есть конфиг файл `/opt/config/auth-config.lua`. Тогда что бы он был доступен через импорт `require('auth-config')` нужно добавить в `/etc/tarantool/instances.available/auth-config` строчку перед импортом `package.path = package.path .. ';/opt/config/?.lua'`.

`no file './/etc/tarantool/instances/available/auth-config/lua.lua' no file './/etc/tarantool/instances/available/auth-config/lua/init.lua'` - похоже ошибка здесь в том что пути относительные.


Для сессий пользователя можно использовать HttpOnly куки. Здесь стоит отметить, что csrf token не имеет никакого отношения к сессии пользователя. Это два разных ключа в cookie которые выполняют разные роли. Защита от CSRF выходит за рамки этой библиотеки.

**Comment by makorne** [comment]
Насколько понял, надо сделать так:
`
package.path = package.path .. ';/etc/tarantool/instances.available/?.lua'

return {
    activation_secret = '`

не работает.
`2018-06-06 19:47:25.813 [11806] main/101/tarantool-authman tarantoolctl:521 E> Start failed: /etc/tarantool/instances.enabled/tarantool-authman.lua:4: module 'auth-config' not found:
        no field package.preload['auth-config']
        no file './auth-config.lua'
        no file './auth-config/init.lua'
        no file './auth-config.so'
`

ПОнятно что csrf защита не входит. 
Но куда вы обычно полученный из апи ключ сессии засовываете?  В куки? Прямо вот такой здоровенный?
Просто в той статье на хабре заявляется что вообще куки для сессии нельзя использовать, ибо не защитить, а как решение - сувать только в headers.
 А во второй статье ровно наоборот...

**Comment by LinnikD** [comment]
`package.path = package.path .. ';/etc/tarantool/instances.available/?.lua'` - эта строка должна быть в первом исполняемом файле, те в `tarantool-authman.lua` до строки с `require('auth-config')`.

Да, сессионный ключ я обычно складываю в куки. Статья на хабре ссылается на то что это может повысить риск успешных csrf атак, поэтому я и говорю что обеспечивать защиту от csrf нужно другими механизмами, о них в статье тоже написано.

**Comment by makorne** [comment]
Спасибо, так запустилось.

А в статье написано что все способы на куках - уязвимы, и вывод -
`правильно защититься от CSRF - не использовать cookies для управления пользовательской сессией"...
